In [1]:
import pandas as pd 
import numpy as np

In [2]:
arr1 = np.arange(2,41,2).reshape(4,5)
arr1

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [3]:
df2 = pd.DataFrame(arr1)
df2.columns = ["C1","C2","C3","C4","C5"]
df2

   C1  C2  C3  C4  C5
0   2   4   6   8  10
1  12  14  16  18  20
2  22  24  26  28  30
3  32  34  36  38  40

# To  Ganerate the Student Data Frame 
## (Roll No , name ,marks , gender)

In [4]:
Students = pd.DataFrame([
    [101, "Sahil", 70, "M"],
    [102, "Jai", 80, "M"],
    [103, "Saurav", 56, "M"]
],
columns=["RollNo", "Name", "Marks", "Gender"])

Students

   RollNo    Name  Marks Gender
0     101   Sahil     70      M
1     102     Jai     80      M
2     103  Saurav     56      M

In [5]:
Employees = pd.DataFrame({"Eid":[101,102,103,104],
                          "Ename":["Sahil","Saurav","Jai","Youraj"],
                          "Salary":[10000,20000,30000,20000],
                          "Location":["Pune","Mumbai","A.Nager","Banglore"]})
Employees

   Eid   Ename  Salary  Location
0  101   Sahil   10000      Pune
1  102  Saurav   20000    Mumbai
2  103     Jai   30000   A.Nager
3  104  Youraj   20000  Banglore

In [6]:

details = pd.DataFrame({"Intake":[120,60,120,60],
                        "Admitted":[118,50,100,55]},
                       index =["Mech","Civil","Comp","E&TC"])

details

       Intake  Admitted
Mech      120       118
Civil      60        50
Comp      120       100
E&TC       60        55

# Addding / removing columns or rows

In [7]:
# details['Vacant']=[2,10,30,5]

In [8]:
details['Vacant'] = details['Intake']- details['Admitted']
details

       Intake  Admitted  Vacant
Mech      120       118       2
Civil      60        50      10
Comp      120       100      20
E&TC       60        55       5

In [9]:
details

       Intake  Admitted  Vacant
Mech      120       118       2
Civil      60        50      10
Comp      120       100      20
E&TC       60        55       5

In [10]:
Employees['Address'] = ["Pune","Mumbai","Pune","Nasik"]

In [11]:
Employees['Gender'] = ['M','F','M','m']

In [12]:
Employees

   Eid   Ename  Salary  Location Address Gender
0  101   Sahil   10000      Pune    Pune      M
1  102  Saurav   20000    Mumbai  Mumbai      F
2  103     Jai   30000   A.Nager    Pune      M
3  104  Youraj   20000  Banglore   Nasik      m

In [13]:
Employees.loc[4]=[105,"Ganesh",24000,"Nagpur","M"]

ValueError: cannot set a row with mismatched columns

In [ ]:
Student

In [ ]:
Student

In [ ]:
Students

In [ ]:
Students = Students.drop("Gender",axis=1)

In [ ]:
Students

In [ ]:
Students.drop("Marks",axis=1,inplace=True)

In [ ]:
Students

In [ ]:
Students.drop(1,inplace=True)
Students

In [ ]:
details

In [ ]:
details.drop(["Civil","E&TC"])

In [ ]:
details

In [ ]:
details[['Comp','E&TC']]

In [ ]:
details

In [ ]:
details.loc[["Mech","Civil"]]

In [ ]:
df2

# Indexing and slicing  in dataframe

In [ ]:
df2[["C1","C2"]]

In [ ]:
df2.loc[[0,3],["C3","C5"]]

In [ ]:
df2[df2.iloc[:, 1] % 2 == 0]

In [ ]:
df2[df2['C1'] % 2 == 0]

In [ ]:
Employees

In [ ]:
Employees[Employees['Address']=="Pune"]

In [ ]:
Employees[Employees['Gender']=="F"]

##  People with salary more than 25000 and living in pune (Using and &)

Employees[(Employees['Salary']>25000) & (Employees['Address']=="Pune")]

# Adding the new column to dataframe dno

In [ ]:
Employees["dno"]=[1,1,2,2]

In [ ]:
Employees

## Q > Findout the name and salary of employees in dno 2

In [ ]:
Employees[Employees['dno']==2][["Ename","Salary"]]

# Q > Find out the salary of the all the female emp

In [ ]:
Employees[Employees['Gender']=='F'][['Ename','Salary']]

In [ ]:
details

# Q > Findout the How many  Percent Addmission completed in each department

In [ ]:
details[details['Admitted']/details['Intake']*100>95]

In [ ]:
Employees

# Q > To change the salary of the jai employee to 31000

In [ ]:
Employees.loc[Employees['Ename']=="Jai","Salary"]=31000

In [ ]:
Employees

# To Change the salary of the both the employees

In [ ]:
Employees.loc[(Employees['Ename'] == "Sahil") | (Employees['Ename'] == "Saurav"), "Salary"] = 50000

In [ ]:
Employees

In [ ]:
Employees.loc[Employees['Address']=="Pune",'dno']=np.nan

In [ ]:
Employees

## Function in dataframes

In [ ]:
df1 = pd.DataFrame(np.arange(1,11).reshape(2,5))
df2 = pd.DataFrame(np.arange(21,31).reshape(2,5))

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1+df2

In [ ]:
df1.columns=["A","B","C","D","E"]
df2.columns=["C","D","E","F","G"]

In [ ]:
df1+df2

In [ ]:
list1=["Dno","Name","Address"]
dept = pd.DataFrame(list1)

In [ ]:
dept

In [ ]:
dept = pd.DataFrame([[1,'It','Pune'],
                    [2,'HR','Nasik'],
                    [3,'SCM',"Nagpur"],
                    [4,'Software','Pune']],
                    columns=['Dno','Name','Address']
                    )
dept

In [ ]:
pd.concat([df1,df2],axis=1)

In [ ]:
Employees

In [ ]:
dept

In [ ]:
pd.concat([Employees,dept],axis=1)

# GroupBy and Count method

In [14]:
Employees.groupby('Gender')['Gender'].count()

Gender
F    1
M    2
m    1
Name: Gender, dtype: int64

In [15]:
Employees.groupby('Gender')['Salary'].max()

Gender
F    20000
M    30000
m    20000
Name: Salary, dtype: int64

In [19]:
Employees.groupby('dno')['Salary'].mean()

dno
1    15000.0
2    25000.0
Name: Salary, dtype: float64

In [17]:
Employees

   Eid   Ename  Salary  Location Address Gender
0  101   Sahil   10000      Pune    Pune      M
1  102  Saurav   20000    Mumbai  Mumbai      F
2  103     Jai   30000   A.Nager    Pune      M
3  104  Youraj   20000  Banglore   Nasik      m

In [18]:
Employees['dno']=[1,2,2,1]
Employees

   Eid   Ename  Salary  Location Address Gender  dno
0  101   Sahil   10000      Pune    Pune      M    1
1  102  Saurav   20000    Mumbai  Mumbai      F    2
2  103     Jai   30000   A.Nager    Pune      M    2
3  104  Youraj   20000  Banglore   Nasik      m    1

In [20]:
Employees['Address']

0      Pune
1    Mumbai
2      Pune
3     Nasik
Name: Address, dtype: object

In [21]:
Employees['Address'].unique()

array(['Pune', 'Mumbai', 'Nasik'], dtype=object)

In [22]:
Employees['Address'].nunique()

3

# Findout the no.of employees in each address 
## With the help of the groupby Method

In [23]:
Employees.groupby("Address")["Address"].count()

Address
Mumbai    1
Nasik     1
Pune      2
Name: Address, dtype: int64

# With help of the .Value_counts() Method

In [24]:
Employees["Address"].value_counts()

Address
Pune      2
Mumbai    1
Nasik     1
Name: count, dtype: int64